version: '3'
services:
  lagou-nginx:
    image: nginx:1.19.3-alpine
    container_name: lagou-nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - /data/nginx:/etc/nginx
  lagou-tomcat1:
    image: tomcat:9.0.20-jre8-alpine
    container_name: lagou-tomcat1
    restart: always
    ports:
      - 8081:8080
    volumes:
      - /data/tomcat1/webapps:/usr/local/tomcat/webapps
    depends_on:
      - lagou-nginx
  lagou-tomcat2:
    image: tomcat:9.0.20-jre8-alpine
    container_name: lagou-tomcat2
    restart: always
    ports:
      - 8082:8080
    volumes:
      - /data/tomcat2/webapps:/usr/local/tomcat/webapps
    depends_on:
      - lagou-nginx