server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://192.168.75.130:3307/lagou?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8

mybatis-plus:
  type-aliases-package: com.snail.entity
  mapper-locations: mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #配置日志打印方式。不使用mybatis的日志信息。使用mp的日志配置